
apiVersion: v1
kind: Secret 
metadata: 
  name: aws-cred
data: 
  aws_access_key_id: QUtJQVhDSUFNUldMSVU2V1VNMlI=
  aws_secret_access_key: c1BrZzNqTGFZWkY0bUQraTBuNVR3ZDRrd3FHNjh3ME41SU5xL2g1cA==
  aws_default_region: dXMtZWFzdC0x
