apiVersion: batch/v1
kind: Job
metadata:
  generateName: run-script
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: run-script
        image: asatiaayushi/run-script   
        command: ["bin/sh" , "-c"]
        args: ["script.sh"]
        restartPolicy: Never
  backoffLimit: 2
