apiVersion: batch/v1
kind: Job
metadata:
  generateName: run-script
  annotations:
    argocd.argoproj.io/hook: PostSync
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      volumes: 
        - name: script 
          hostPath: /app/login_cli.sh
      containers:
        - name: aws-cli
          image: asatiaayushi/aws-cli-2
          volumeMounts: 
            - name : script
              mountPath: /script
          command: 
            - sh
            - login_cli.sh
      restartPolicy: Never
  backoffLimit: 2 
