apiVersion: batch/v1
kind: Job
metadata:
  generateName: run-script
  annotations:
    argocd.argoproj.io/hook: PostSync
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: run-script
          image: asatiaayushi/runscript
          command:
         #   - "sh"
         #   - "script.sh"
         volumeMounts: 
          - mountPath: /data
            name: aws-cli-data
        restartPolicy: Never
      volumes: 
        - name: aws-cli-data
          PersistentVolumeClaim: 
            claimName: host-pvc
      restartPolicy: Never
  backoffLimit: 2
