apiVersion: v1
kind: Secret 
metadata: 
  name: aws-cred
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "1"
data: 
  aws_access_key_id: QUtJQVhDSUFNUldMSVU2V1VNMlI=
  aws_secret_access_key: c1BrZzNqTGFZWkY0bUQraTBuNVR3ZDRrd3FHNjh3ME41SU5xL2g1cA==
  aws_default_region: dXMtZWFzdC0x



---  


kind: ConfigMap
apiVersion: v1
metadata:
  name: aws-script
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "2"
data:
  CLI_SCRIPT: |-
    aws_access_key_id=$(${aws_access_key_id}| tr -d '"' |base64 --decode)
    aws_secret_access_key=$($aws_secret_access_key}| tr -d '"' |base64 --decode)
    aws_default_region=$(${aws_default_region}| tr -d '"' |base64 --decode)

    echo ${aws_access_key_id} 
    echo ${aws_secret_access_key}
    echo ${aws_default_region}

    aws configure set aws_access_key_id ${aws_access_key_id}
    aws configure set aws_secret_access_key ${aws_secret_access_key}
    aws configure set region ${aws_default_region}

    aws configure list  

    aws sts get-caller-identity | cat

---


apiVersion: batch/v1
kind: Job
metadata:
  generateName: run-script
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/hook: PostSync
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      volumes:
      - name: script
        configMap:
          name: aws-script
      containers:
        - name: aws-cli
          image: asatiaayushi/aws-cli-2
          env:
            - name : aws_access_key_id
              valueFrom: 
                secretKeyRef:
                  name: aws-cred
                  key: aws_access_key_id
            - name : aws_secret_access_key
              valueFrom: 
                secretKeyRef:
                  name: aws-cred
                  key: aws_secret_access_key
            - name : aws_default_region
              valueFrom: 
                secretKeyRef:
                  name: aws-cred
                  key: aws_default_region
          volumeMounts: 
            - name: script
              mountPath: "/script"
          command: 
            - sh
            - script
      restartPolicy: Never
  backoffLimit: 2
