apiVersion: v1
kind: Secret 
metadata: 
  name: aws-cred
 # annotations:
    #argocd.argoproj.io/sync-wave: "1"
data: 
  aws_access_key_id: QUtJQVhDSUFNUldMSVU2V1VNMlI=
  aws_secret_access_key: c1BrZzNqTGFZWkY0bUQraTBuNVR3ZDRrd3FHNjh3ME41SU5xL2g1cA==
  aws_default_region: dXMtZWFzdC0x



---  


apiVersion: batch/v1
kind: Job
metadata:
  generateName: run-script
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook: PostSync
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: aws-cli
          image: asatiaayushi/aws-cli-2
          env:
            - name : aws_access_key_id
              valueFrom: 
                secretKeyRef:
                  name: aws-cred
                  key: aws_access_key_id
            - name : aws_secret_access_key
              valueFrom: 
                secretKeyRef:
                  name: aws-cred
                  key: aws_secret_access_key
            - name : aws_default_region
              valueFrom: 
                secretKeyRef:
                  name: aws-cred
                  key: aws_default_region
          command: ["/bin/sh","login_aws_cli.sh"]
      restartPolicy: Never
  backoffLimit: 2
