apiVersion: batch/v1
kind: Job
metadata:
  generateName: run-script
  annotations:
    argocd.argoproj.io/hook: PostSync
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: aws-cli
          image: amazon/aws-cli:latest
          command: ["sh","-c"]
          args: 
            - aws configure set aws_access_key_id ${aws_access_key_id}
            - aws configure set aws_secret_access_key ${aws_secret_access_key}
            - aws configure set region ${aws-cred}
            - aws configure set output json
      env: 
        - name: aws_access_key_id
          valueFrom: 
            secretKeyRef: 
              name: aws-cred
              key:  aws_access_key_id
        - name: aws_access_key_id
          valueFrom: 
            secretKeyRef: 
              name: aws-cred
              key: aws_secret_access_key
        - name: aws_default_region
          valueFrom: 
            secretKeyRef: 
              name: aws-cred
              key: aws_default_region
      restartPolicy: Never
  backoffLimit: 2
