apiVersion: batch/v1
kind: Job
metadata:
  generateName: run-script
  annotations:
    argocd.argoproj.io/hook: PostSync
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: aws-cli
          image: amazon/aws-cli:latest
          command: ["sh","-c"]
          args: 
          - aws configure set aws_access_key_id AKIAXCIAMRWLIU6WUM2R
            aws configure set aws_secret_access_key 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
            aws configure set region eu-west-1
            aws configure set output json
      restartPolicy: Never
  backoffLimit: 2
